apiVersion: v1
kind: App
name: mailmate-server-staging
region: sgp

services:
  - name: api
    image: registry.digitalocean.com/mosh-do-docker-reg/mailmate-server:staging
    run_command: "npm run staging"
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: staging
      - key: PORT
        value: "3500"
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DATABASE_HOST
        value: ${DATABASE_HOST}
      - key: DATABASE_USER
        value: ${DATABASE_USER}
      - key: DATABASE_PASSWORD
        value: ${DATABASE_PASSWORD}
      - key: DATABASE_NAME
        value: ${DATABASE_NAME}
      - key: DATABASE_PORT
        value: "${DATABASE_PORT}"
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
      - key: GOOGLE_CLIENT_SECRET
        value: ${GOOGLE_CLIENT_SECRET}
      - key: GOOGLE_CALLBACK_URL
        value: ${GOOGLE_CALLBACK_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: JWT_REFRESH_SECRET
        value: ${JWT_REFRESH_SECRET}
      - key: ENCRYPTION_KEY
        value: ${ENCRYPTION_KEY}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
      - key: LOG_LEVEL
        value: ${LOG_LEVEL}
      - key: ELASTICSEARCH_URL
        value: ${ELASTICSEARCH_URL}
      - key: LOGSTASH_HOST
        value: ${LOGSTASH_HOST}
      - key: LOGSTASH_PORT
        value: "${LOGSTASH_PORT}"
    http_port: 3500
